# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'MaxIM' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  # Pods for MaxIM
  pod 'SDWebImage', '~> 4.2.2'
  pod 'Toast', '~> 3.0'
  pod 'M80AttributedLabel', '~> 1.6.3'
  pod 'TZImagePickerController', '~> 1.9.3'
  pod 'MJExtension'
  pod 'TSActionAlertView'
  pod 'MBProgressHUD'
  pod 'MJRefresh'
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'Bugly'

  pod 'floo-ios'
  
  pod 'FMDB'
  
  target 'MaxIMTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'MaxIMUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
