# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

project 'MaxIM.xcodeproj'
target 'MaxIM' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  # Pods for MaxIM
  pod 'SDWebImage'
  pod 'Toast'
  pod 'M80AttributedLabel'
  pod 'TZImagePickerController'
  pod 'MJExtension'
  pod 'TSActionAlertView'
  pod 'MBProgressHUD'
  pod 'MJRefresh'
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'Bugly'
  pod 'tingyunApp'
  pod 'FMDB'
  pod 'CocoaLumberjack'
  pod 'floo-ios', '~> 4.4.3'
  pod 'GoogleWebRTC', '~> 1.1'
  pod 'floo-rtc-ios', '~> 1.2.0'
  pod 'ActionSheetPicker-3.0'
  pod 'SSZipArchive'
  
  target 'MaxIMTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'MaxIMUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
